//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.02 at 01:25:09 AM CET 
//


package org.springframework.schema.web_services;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="bike" type="{http://www.springframework.org/schema/web-services}bike"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bike"
})
@XmlRootElement(name = "getBikeResponse")
public class GetBikeResponse {

    @XmlElement(required = true)
    protected Bike bike;

    /**
     * Gets the value of the bike property.
     * 
     * @return
     *     possible object is
     *     {@link Bike }
     *     
     */
    public Bike getBike() {
        return bike;
    }

    /**
     * Sets the value of the bike property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bike }
     *     
     */
    public void setBike(Bike value) {
        this.bike = value;
    }

}
