//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.12.02 at 02:40:15 AM CET 
//


package org.springframework.schema.web_services;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.springframework.schema.web_services package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetBikeListRequest_QNAME = new QName("http://www.springframework.org/schema/web-services", "getBikeListRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.springframework.schema.web_services
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetBikeRequest }
     * 
     */
    public GetBikeRequest createGetBikeRequest() {
        return new GetBikeRequest();
    }

    /**
     * Create an instance of {@link GetBikeResponse }
     * 
     */
    public GetBikeResponse createGetBikeResponse() {
        return new GetBikeResponse();
    }

    /**
     * Create an instance of {@link Bike }
     * 
     */
    public Bike createBike() {
        return new Bike();
    }

    /**
     * Create an instance of {@link GetBikeListResponse }
     * 
     */
    public GetBikeListResponse createGetBikeListResponse() {
        return new GetBikeListResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Object }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.springframework.org/schema/web-services", name = "getBikeListRequest")
    public JAXBElement<Object> createGetBikeListRequest(Object value) {
        return new JAXBElement<Object>(_GetBikeListRequest_QNAME, Object.class, null, value);
    }

}
