version: '3.7'

services:

  ws-bank:
    restart: on-failure
    image: openjdk:17-slim
    container_name: ws-bank
    command: "java -jar web-service-bank.jar"
    working_dir: /app
    volumes:
      - ../web-service-bank/target/web-service-bank.jar:/app/web-service-bank.jar
    networks:
      - web-service-networks
    ports:
      - 8080
    env_file:
      - .env

  ws-convertor:
    restart: on-failure
    image: openjdk:17-slim
    container_name: ws-convertor
    command: "java -jar web-service-convertor.jar"
    working_dir: /app
    volumes:
      - ../web-service-convertor/target/web-service-convertor.jar:/app/web-service-convertor.jar
    networks:
      - web-service-networks
    ports:
      - 8080
    env_file:
      - .env

  ws-sell:
    restart: on-failure
    image: openjdk:17-slim
    container_name: ws-sell
    command: "java -jar web-service-sell.jar"
    working_dir: /app
    volumes:
      - ../web-service-sell/target/web-service-sell.jar:/app/web-service-sell.jar
    networks:
      - web-service-networks
    ports:
      - 8080
    env_file:
      - .env
    links:
      - ws-convertor:ws-convertor
      - ws-bank:ws-bank
    depends_on:
      - rmi-bike
      - rmi-customer
      - ws-convertor
      - ws-bank

  rmi-bike:
    restart: on-failure
    image: openjdk:17-slim
    container_name: rmi-bike
    command: "java -jar rmi-bike.jar"
    working_dir: /app
    volumes:
      - ../rmi-bike/target/rmi-bike-jar-with-dependencies.jar:/app/rmi-bike.jar
    networks:
      - web-service-networks
    ports:
      - 1099
    env_file:
      - .env
    depends_on:
      - rmi-customer

  rmi-customer:
    restart: on-failure
    image: openjdk:17-slim
    container_name: rmi-customer
    command: "java -jar rmi-customer.jar"
    working_dir: /app
    volumes:
      - ../rmi-customer/target/rmi-customer-jar-with-dependencies.jar:/app/rmi-customer.jar
    networks:
      - web-service-networks
    ports:
      - 1099
    env_file:
      - .env

  rest-api:
    restart: on-failure
    image: openjdk:17-slim
    container_name: rest-api
    command: "java -jar rest-api.jar"
    working_dir: /app
    volumes:
      - ../rest-api/target/rest-api.jar:/app/rest-api.jar
    networks:
      - web-service-networks
    ports:
      - 8080
    env_file:
      - .env
    depends_on:
      - rmi-bike
      - rmi-customer

  web-app:
    restart: on-failure
    build:
      context: ../
      dockerfile: docker/web-app/Dockerfile
    image: web-service/web-app
    container_name: web-app
    command: npm start -- --host 0.0.0.0 --disable-host-check
    ports:
      - 4200
    volumes:
      - ../web-app/:/web-app
      - node_modules:/web-app/node_modules
    networks:
      - web-service-networks
  
  server:
    restart: on-failure
    build:
      context: ../
      dockerfile: docker/server/Dockerfile
    image: web-servive/server
    container_name: web-server
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./server/sites-enabled/:/etc/nginx/sites-enabled/
    networks:
      - web-service-networks
    links:
      - web-app:web-app
      - rest-api:rest-api
    depends_on:
      - web-app
      - rest-api
      - ws-sell
      - ws-convertor

volumes:
  node_modules:

networks:
  web-service-networks:
    driver: bridge